import type { LabCategoryId, LabModuleMeta } from "./types";

const NOW = "2026-09-27T00:00:00.000Z";

const defaultFlags = {
  enabled: false,
  public: false,
  adminOnly: true,
  beta: true,
  maintenanceMode: false,
} as const;

function mod(
  partial: Omit<LabModuleMeta, "flags" | "createdAt" | "updatedAt" | "changelog"> & {
    flags?: Partial<LabModuleMeta["flags"]>;
    changelog?: string[];
  }
): LabModuleMeta {
  return {
    ...partial,
    flags: { ...defaultFlags, ...partial.flags },
    changelog: partial.changelog || [`${partial.version} — Lab registry entry`],
    createdAt: NOW,
    updatedAt: NOW,
  };
}

/** Canonical Lab module catalog — single source for nav + flags + command palette. */
export const LAB_MODULES: LabModuleMeta[] = [
  mod({
    id: "overview",
    name: "Overview",
    nameHu: "Áttekintés",
    category: "overview",
    version: "1.0.0",
    status: "development",
    description: "Irányítópult áttekintés — valós modulállapotok és mérhető jelek.",
    href: "/admin/lab",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "monitor",
    name: "Monitor",
    nameHu: "Monitor",
    category: "monitor",
    version: "1.0.0",
    status: "live",
    description: "Látogatottság, SEO Monitor és GSC indexelés — admin irányítópult.",
    href: "/admin",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pass",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "action-center",
    name: "Action Center",
    nameHu: "Action Center",
    category: "action-center",
    version: "1.0.0",
    status: "development",
    description: "Prioritásos teendők valós forrásokból (SEO, audit, VPS, security).",
    href: "/admin/lab/action-center",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "website-audit",
    name: "Website Audit",
    nameHu: "Weboldal-ellenőrző",
    category: "website-tools",
    version: "1.0.0",
    status: "live",
    description: "SSRF-védett weboldal-ellenőrző a teljes admin felülettel.",
    href: "/admin/website-audit",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pass",
    securityStatus: "pass",
    performanceStatus: "pass",
  }),
  mod({
    id: "seo-lab",
    name: "SEO Lab",
    nameHu: "SEO Lab",
    category: "seo-lab",
    version: "1.0.0",
    status: "development",
    description: "SEO Monitor + GSC indexelés — meglévő motorok Lab felületen.",
    href: "/admin/lab/seo-lab",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
    requiresExternalCreds: ["GSC_CLIENT_EMAIL", "GSC_PRIVATE_KEY"],
  }),
  mod({
    id: "security-center",
    name: "Security Center",
    nameHu: "Security Center",
    category: "security-center",
    version: "1.0.0",
    status: "development",
    description: "Valós biztonsági ellenőrzések (auth, headers, SSRF, indexability).",
    href: "/admin/lab/security-center",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "vps-monitor",
    name: "VPS Monitor",
    nameHu: "VPS Monitor",
    category: "vps-monitor",
    version: "1.0.0",
    status: "development",
    description: "Szerveroldali CPU/RAM/disk/hálózat metrikák (/proc) — admin only.",
    href: "/admin/lab/vps-monitor",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "design-system",
    name: "Design System",
    nameHu: "Design System",
    category: "design-system",
    version: "1.0.0",
    status: "development",
    description: "Token playground — Colors, Typography, Surfaces, Components.",
    href: "/admin/lab/design-system",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pending",
    securityStatus: "n/a",
    performanceStatus: "n/a",
  }),
  mod({
    id: "performance",
    name: "Performance Lab",
    nameHu: "Performance",
    category: "performance",
    version: "0.1.0",
    status: "prototype",
    description: "API latency és audit duration mérések — retentionnel.",
    href: "/admin/lab/performance",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "n/a",
    performanceStatus: "pending",
  }),
  mod({
    id: "calculators",
    name: "Calculator Engine",
    nameHu: "Kalkulátorok",
    category: "calculators",
    version: "0.1.0",
    status: "prototype",
    description: "Konfigurálható kalkulátor motor (Lab-only, nem publikus).",
    href: "/admin/lab/calculators",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pending",
    performanceStatus: "n/a",
  }),
  mod({
    id: "forms-flows",
    name: "Forms & Flows",
    nameHu: "Űrlapok",
    category: "forms-flows",
    version: "0.2.0",
    status: "prototype",
    description:
      "Űrlap szerkesztő, feltételes mezők, élő előnézet és lead mentés.",
    href: "/admin/lab/forms-flows",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pending",
    performanceStatus: "n/a",
  }),
  mod({
    id: "client-hub",
    name: "Client Hub",
    nameHu: "Client Hub",
    category: "client-hub",
    version: "0.1.0",
    status: "idea",
    description: "Ügyfél → projekt objektummodell + object-level auth alap.",
    href: "/admin/lab/client-hub",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "pending",
    performanceStatus: "n/a",
  }),
  mod({
    id: "leads-crm",
    name: "Leads / CRM",
    nameHu: "Leadek / CRM",
    category: "leads-crm",
    version: "0.1.0",
    status: "idea",
    description: "Lead lifecycle és attribution architektúra.",
    href: "/admin/lab/leads-crm",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "n/a",
    performanceStatus: "n/a",
  }),
  mod({
    id: "social-hub",
    name: "Social Hub",
    nameHu: "Social Hub",
    category: "social-hub",
    version: "0.1.0",
    status: "idea",
    description: "Platform adapter architektúra — publish alapból dry-run.",
    href: "/admin/lab/social-hub",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "pending",
    performanceStatus: "n/a",
    requiresExternalCreds: [
      "META_APP_ID",
      "LINKEDIN_CLIENT_ID",
      "X_API_KEY",
    ],
  }),
  mod({
    id: "care-monitor",
    name: "Care Monitor",
    nameHu: "Care Monitor",
    category: "care-monitor",
    version: "0.1.0",
    status: "idea",
    description: "Ügyfél-oldalak uptime/SSL/SEO figyelése.",
    href: "/admin/lab/care-monitor",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "pending",
    performanceStatus: "n/a",
  }),
  mod({
    id: "analytics",
    name: "Analytics",
    nameHu: "Analytics",
    category: "analytics",
    version: "0.1.0",
    status: "prototype",
    description: "Belső analytics store + GSC ready — nincs fake dashboard szám.",
    href: "/admin/lab/analytics",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "automation",
    name: "Automation",
    nameHu: "Automation",
    category: "automation",
    version: "0.1.0",
    status: "idea",
    description: "Trigger → Conditions → Actions — no arbitrary code exec.",
    href: "/admin/lab/automation",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "pending",
    performanceStatus: "n/a",
  }),
  mod({
    id: "ai-tools",
    name: "AI Tools",
    nameHu: "AI Tools",
    category: "ai-tools",
    version: "0.1.0",
    status: "idea",
    description: "Detect → Recommend → Preview Diff → Approve — no auto-publish.",
    href: "/admin/lab/ai-tools",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "pending",
    performanceStatus: "n/a",
    requiresExternalCreds: ["AI_API_KEY"],
  }),
  mod({
    id: "experiments",
    name: "Experiments",
    nameHu: "Kísérletek",
    category: "experiments",
    version: "0.1.0",
    status: "idea",
    description: "Feature kísérletek sandbox.",
    href: "/admin/lab/experiments",
    implemented: false,
    flags: { enabled: true },
    testStatus: "n/a",
    securityStatus: "n/a",
    performanceStatus: "n/a",
  }),
  mod({
    id: "testing-qa",
    name: "Testing / QA",
    nameHu: "Testing / QA",
    category: "testing-qa",
    version: "0.1.0",
    status: "prototype",
    description: "Teszt suite státusz és production readiness checklist.",
    href: "/admin/lab/testing-qa",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "n/a",
    performanceStatus: "n/a",
  }),
  mod({
    id: "debug",
    name: "Debug",
    nameHu: "Debug",
    category: "debug",
    version: "0.1.0",
    status: "prototype",
    description: "Sanitized request/response panel — titkok maszkolva.",
    href: "/admin/lab/debug",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "logs",
    name: "Logs",
    nameHu: "Naplók",
    category: "logs",
    version: "0.1.0",
    status: "prototype",
    description: "Structured security audit log (érzékeny műveletek).",
    href: "/admin/lab/logs",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "integrations",
    name: "Integrations",
    nameHu: "Integrációk",
    category: "integrations",
    version: "0.1.0",
    status: "prototype",
    description: "Külső szolgáltatások setup állapota — credential nélkül UNAVAILABLE.",
    href: "/admin/lab/integrations",
    implemented: true,
    flags: { enabled: true },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "settings",
    name: "Lab Settings",
    nameHu: "Beállítások",
    category: "settings",
    version: "1.0.0",
    status: "development",
    description: "Feature flagek, kill switch, dashboard widgetek.",
    href: "/admin/lab/settings",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
  mod({
    id: "promo-offers",
    name: "Promo Offers",
    nameHu: "Akciós ajánlatok",
    category: "content",
    version: "1.1.0",
    status: "development",
    description:
      "Akciós árak csoportosan (web 25%, egyedi 10%, támogatás nélkül).",
    href: "/admin/lab/promo-offers",
    implemented: true,
    flags: { enabled: true, beta: false },
    testStatus: "pending",
    securityStatus: "pass",
    performanceStatus: "n/a",
  }),
];

export const LAB_CATEGORY_LABELS: Record<LabCategoryId, string> = {
  overview: "Áttekintés",
  monitor: "Monitor",
  favorites: "Kedvencek",
  recent: "Recent",
  "action-center": "Action Center",
  "website-tools": "Weboldal-eszközök",
  "seo-lab": "SEO Lab",
  "security-center": "Security Center",
  performance: "Performance",
  "vps-monitor": "VPS Monitor",
  calculators: "Kalkulátorok",
  "forms-flows": "Űrlapok",
  "client-hub": "Client Hub",
  "care-monitor": "Care Monitor",
  "social-hub": "Social Hub",
  content: "Tartalom",
  analytics: "Analytics",
  "leads-crm": "Leadek / CRM",
  automation: "Automation",
  "ai-tools": "AI Tools",
  "design-system": "Design System",
  experiments: "Experiments",
  "testing-qa": "Testing / QA",
  debug: "Debug",
  logs: "Logs",
  integrations: "Integrations",
  settings: "Beállítások",
};

export function getLabModule(id: string): LabModuleMeta | undefined {
  return LAB_MODULES.find((m) => m.id === id);
}

export function listLabModulesByCategory(): Array<{
  category: LabCategoryId;
  label: string;
  modules: LabModuleMeta[];
}> {
  const order: LabCategoryId[] = [
    "overview",
    "monitor",
    "action-center",
    "website-tools",
    "seo-lab",
    "security-center",
    "vps-monitor",
    "performance",
    "design-system",
    "calculators",
    "forms-flows",
    "client-hub",
    "leads-crm",
    "social-hub",
    "care-monitor",
    "content",
    "analytics",
    "automation",
    "ai-tools",
    "experiments",
    "testing-qa",
    "debug",
    "logs",
    "integrations",
    "settings",
  ];
  return order
    .map((category) => ({
      category,
      label: LAB_CATEGORY_LABELS[category],
      modules: LAB_MODULES.filter((m) => m.category === category),
    }))
    .filter((g) => g.modules.length > 0);
}
